import logoImage from '../images/logo.jpg'
import Head from "next/head";
import styles from '../styles/Header.module.scss'
import {HeaderLink} from "./HeaderLink";

export const Header = ({children}) => {
    return (
        <>
            <Head>
                <title>Calendar</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <header>
                <div className={styles.container}>
                    <img src={logoImage} alt="logo"/>
                    <nav>
                        <ul className={styles.nav}>
                            <HeaderLink link={'/'} text={'Home'}/>
                            <HeaderLink link={'/about'} text={'About Us'}/>
                        </ul>
                    </nav>
                </div>
            </header>
            {children}
        </>
    )
}